import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import myImage from "../public/myImage.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mani Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-wheat px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedby</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 "
                  target="_blank" href="/Resume.pdf"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:mt-0 md:h-96 md:w-96">
              <Image src={myImage} layout="fill" objectFit="cover" alt="myImage" />

            </div>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Mani bharadwaj
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              FullstackDeveloper
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Full-stack developer and designer, passionate about creating innovative solutions. Lets connect and explore opportunities!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
  <a target="_blank"  href="https://github.com/Manibhardawaj"  rel="noreferrer">
    <AiFillGithub />
  </a>
  <a target="_blank" href="https://www.linkedin.com/in/mani-bharadwaj" rel="noreferrer">
    <AiFillLinkedin />
  </a>
  <a target="_blank" href="mailto:manibharadwajcr@gmail.com" rel="noreferrer">
    <AiFillMail />
  </a>
</div>

            
        </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            In the digital realm, I am an aspiring professional with a focus on design and development. I have had the privilege of working with an organization and collaborating with talented individuals. Together, we have created digital products that cater to both businesses and consumers. I am eager to secure a position where I can apply my skills, continue to learn, and grow.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services in 
              programming.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
              Design Implementation
              </h3>
              <p className="py-2">
              
              Crafting visually appealing solutions that adhere to fundamental design principles</p>
              <h4 className="py-4 text-teal-600"> Tools I Use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">Chrome DevTools </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100}  alt="code"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Nextjs</p>
              <p className="text-gray-800 py-1">Visual studio </p>
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">MERN</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="consulting" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
              Need quick, actionable insights for your coding project? Lets enhance it together!
</p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Azure</p>
              <p className="text-gray-800 py-1">Thunder client</p>
              <p className="text-gray-800 py-1"> MongoDB</p>
              <p className="text-gray-800 py-1">Nodejs</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            As a developer with a focus on frontend, I’ve worked on a variety of projects that demonstrate my skills and passion. These projects range from creating interactive web applications to designing user-friendly interfaces. Each project is a testament to my commitment, hardwork to quality and my coding interest.            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Check Out Below.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <a href="https://myyoutubecom.netlify.app/" target="_blank" rel="noopener noreferrer">

            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="Web 1"
              />
            </div>
          </a>
            <a href="https://mydisney-clone-v1.netlify.app/" target="_blank" rel="noopener noreferrer">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="Web 2" 
              />
            </div>
            </a>
            <a href="https://mydice-game21.netlify.app/" target="_blank" rel="noopener noreferrer">
            
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="Web 3" 
              />
            </div>
            </a>
            <a href="https://mymusic-player1.netlify.app/" target="_blank" rel="noopener noreferrer">

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="Web 4" 
              />
            </div>
            </a>
            <a href="https://manibhardawaj.github.io/Analog_clock/" target="_blank" rel="noopener noreferrer">
            
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="Web 5" 
              />
            </div>
            </a>
            <a href="https://github.com/Manibhardawaj" target="_blank" rel="noopener noreferrer">
            
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="Web 6" 
              />
            </div>
    </a>
          </div>
        </section>
      </main>

      <footer className="text-center">
  <div className="border-t border-gray-300 py-2">
    <p className="text-gray-600">
      Phone: <a href="tel:+91 9632453556">+91 9632453556</a>
    </p>
      <p className="text-gray-600">
      Email: <a href="mailto:manibharadwajcr@gmail.com">manibharadwajcr@gmail.com</a>
      </p>
  </div>
</footer>
    </div>
  );
}
